version: "3.7"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      #- "/app/node_modules"
    env_file:
      - .env
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
